#For Cisco
cisco_user: username
cisco_password: SuperStrongPassword
cisco_become_password: SuperStrongPassword

#For Mikrotik
mikrotik_user: username
mikrotik_password: SuperStrongPassword

#If you password start with numbers, make sure to surround it with quotation, if not ansible will treat it like an interger
