- name: Cisco | Check SSH Status
  cisco.ios.ios_command:
    commands:
      - show ip ssh
  become: yes
  become_method: enable
  register: ssh_status

- name: Cisco | Fail if SSH v2 is not active
  fail:
    msg: "NON-COMPLIANT: SSH version 2.0 is not active on {{ inventory_hostname }}"
  when: not (ssh_status.stdout[0] | lower | regex_search('version 2\.0'))
